$SERVER = "192.168.1.170,1433"
$DATABASE = "uPhotoMD"
$USER = "sa"
$PASSWORD = "34m@^25DophSG#ZGuzeN"

sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i "..\Tables\AccountType.sql"
sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i "..\Tables\Tag.sql"
sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i "..\Tables\Privilege.sql"
sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i "..\Tables\MimeType.sql"
sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i "..\Tables\GeographicalLocationType.sql"
sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i "..\Tables\UserAccount.sql"
sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i "..\Tables\Album.sql"
sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i "..\Tables\GeographicalLocation.sql"
sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i "..\Tables\Photo.sql"
sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i "..\Tables\PhotoTag.sql"
sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i "..\Tables\UserAlbumAccess.sql"
sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i "..\Tables\AlbumAccessPrivilege.sql"